### ISSUE TITLE
Many parallel ops crash engine

### ISSUE THREAD

**Issue by chrisdostert** [opspec-io/engine#17]
When running many parallel ops 20-30, the engine will become unresponsive and eventually crash. 
```SHELL
$ docker logs opctl_engine
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xc0 pc=0x570f07]

goroutine 8 [running]:
panic(0x860d40, 0xc82000a090)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/opctl/engine/tcp/models.NewEventMsg(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/opctl/engine/tcp/models/eventMsg.go:16 +0x107
github.com/opctl/engine/tcp.getEventStreamHandler.ServeHTTP.func3(0xc8202800e0, 0xc8201c6de0, 0x7fb8c300d0e0, 0xc82027a270, 0xc82006fc00)
	/go/src/github.com/opctl/engine/tcp/getEventStreamHandler.go:66 +0xf5
created by github.com/opctl/engine/tcp.getEventStreamHandler.ServeHTTP
	/go/src/github.com/opctl/engine/tcp/getEventStreamHandler.go:80 +0x2cd
```

**Comment by chrisdostert** [comment]
this was caused by docker-machine not being started with sufficient resources to run the number of containers required to carry out the op.
